export const GAME_STATES = {
  IDLE: "IDLE",
  SEARCHING: "SEARCHING",
  LOADING: "LOADING",
  PLAYING: "PLAYING",
};

export const PLAYER_STATES = {
  PLAYING: "PLAYING",
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  VALIDATING: "VALIDATING",
  DISCONNECTED: "DISCONNECTED",
};
